version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: mongodbname
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'mongodbname'
      ME_CONFIG_MONGODB_AUTH_USERNAME: 'admin'
      ME_CONFIG_MONGODB_AUTH_PASSWORD: 'admin123'
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/?authSource=admin

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/mongodbname?authSource=admin
    volumes:
      - ./src:/app/src 
      - /app/node_modules 

volumes:
  mongodb_data:
